In [24]:
import numpy as np
from game_to_simplex import game_to_simplex_table
from simplex_method import simplex_method
import game_to_simplex

In [25]:
A = np.array([[2, 5, 4], [7, 0, 6]])
A = game_to_simplex_table(A)
print(A)


[[ 2.  5.  4.  1.]
 [ 7.  0.  6.  1.]
 [-1. -1. -1.  0.]]


In [26]:
z = simplex_method(A) #return [0]=value table, [1]=position
print(f"Tableau:\n {z[0]}")
print()
print(f"Position of the variables: {z[1]}")

Tableau:
 [[-0.05714286  0.2         0.45714286  0.14285714]
 [ 0.14285714 -0.          0.85714286  0.14285714]
 [ 0.08571429  0.2         0.31428571  0.28571429]]

Position of the variables: [5 4 3 2 1]


In [27]:
game_result = game_to_simplex.simplex_to_game_result(z[0], z[1]) #return [0]=game_value, [1]=column prob, [2]=row prob
print(f"Game Value: {game_result[0]}")
print(f"Columns Prob: {game_result[1]}")
print(f"Rows Prob: {game_result[2]}")

Game Value: 3.5
Columns Prob: [[0.5 0.5 0. ]]
Rows Prob: [[0.7 0.3]]
